public static List<String> caredVulns = Arrays.asList(
        "COMMAND_INJECTION",
        "XSS_JSP_PRINT", "XSS_REQUEST_WRAPPER", "XSS_SERVLET",
        "URLCONNECTION_SSRF_FD",
        "SQL_INJECTION_HIBERNATE", "SQL_INJECTION_JDO", "SQL_INJECTION_JPA",
        "SQL_INJECTION_JDBC", "SQL_INJECTION_SPRING_JDBC",
        "SQL_INJECTION_TURBINE",
        "UNVALIDATED_REDIRECT",
        "LDAP_INJECTION",
        "XPATH_INJECTION");
